// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	reminder "looklook/app/reminder/cmd/api/internal/handler/reminder"
	"looklook/app/reminder/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// reminder create
				Method:  http.MethodPost,
				Path:    "/reminder/create",
				Handler: reminder.CreateReminderHandler(serverCtx),
			},
			{
				// reminder delete
				Method:  http.MethodPost,
				Path:    "/reminder/delete",
				Handler: reminder.DeleteReminderHandler(serverCtx),
			},
			{
				// 修改提醒状态
				Method:  http.MethodPost,
				Path:    "/reminder/done",
				Handler: reminder.DoneReminderedHandler(serverCtx),
			},
			{
				// reminder list
				Method:  http.MethodGet,
				Path:    "/reminder/list",
				Handler: reminder.ReminderListHandler(serverCtx),
			},
			{
				// reminder modify
				Method:  http.MethodPost,
				Path:    "/reminder/modify",
				Handler: reminder.ModifyReminderHandler(serverCtx),
			},
			{
				// 通过id获取reminder
				Method:  http.MethodGet,
				Path:    "/reminder/reminderById",
				Handler: reminder.ReminderByIdHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/reminder/v1"),
	)
}
