// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: signin.proto

package signin

import (
	"context"

	"looklook/app/signin/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRecodeReq          = pb.AddRecodeReq
	AddRecodeResp         = pb.AddRecodeResp
	AddTaskFinishReq      = pb.AddTaskFinishReq
	AddTaskFinishResp     = pb.AddTaskFinishResp
	AddTaskReq            = pb.AddTaskReq
	AddTaskResp           = pb.AddTaskResp
	DelRecodeReq          = pb.DelRecodeReq
	DelRecodeResp         = pb.DelRecodeResp
	DelTaskFinishReq      = pb.DelTaskFinishReq
	DelTaskFinishResp     = pb.DelTaskFinishResp
	DelTaskReq            = pb.DelTaskReq
	DelTaskResp           = pb.DelTaskResp
	GetRecodeByIdReq      = pb.GetRecodeByIdReq
	GetRecodeByIdResp     = pb.GetRecodeByIdResp
	GetTaskByIdReq        = pb.GetTaskByIdReq
	GetTaskByIdResp       = pb.GetTaskByIdResp
	GetTaskFinishByIdReq  = pb.GetTaskFinishByIdReq
	GetTaskFinishByIdResp = pb.GetTaskFinishByIdResp
	Recode                = pb.Recode
	SearchRecodeReq       = pb.SearchRecodeReq
	SearchRecodeResp      = pb.SearchRecodeResp
	SearchTaskFinishReq   = pb.SearchTaskFinishReq
	SearchTaskFinishResp  = pb.SearchTaskFinishResp
	SearchTaskReq         = pb.SearchTaskReq
	SearchTaskResp        = pb.SearchTaskResp
	Task                  = pb.Task
	TaskFinish            = pb.TaskFinish
	UpdateRecodeReq       = pb.UpdateRecodeReq
	UpdateRecodeResp      = pb.UpdateRecodeResp
	UpdateTaskFinishReq   = pb.UpdateTaskFinishReq
	UpdateTaskFinishResp  = pb.UpdateTaskFinishResp
	UpdateTaskReq         = pb.UpdateTaskReq
	UpdateTaskResp        = pb.UpdateTaskResp

	Signin interface {
		// -----------------------recode-----------------------
		AddRecode(ctx context.Context, in *AddRecodeReq, opts ...grpc.CallOption) (*AddRecodeResp, error)
		UpdateRecode(ctx context.Context, in *UpdateRecodeReq, opts ...grpc.CallOption) (*UpdateRecodeResp, error)
		DelRecode(ctx context.Context, in *DelRecodeReq, opts ...grpc.CallOption) (*DelRecodeResp, error)
		GetRecodeById(ctx context.Context, in *GetRecodeByIdReq, opts ...grpc.CallOption) (*GetRecodeByIdResp, error)
		SearchRecode(ctx context.Context, in *SearchRecodeReq, opts ...grpc.CallOption) (*SearchRecodeResp, error)
		// -----------------------task-----------------------
		AddTask(ctx context.Context, in *AddTaskReq, opts ...grpc.CallOption) (*AddTaskResp, error)
		UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskResp, error)
		DelTask(ctx context.Context, in *DelTaskReq, opts ...grpc.CallOption) (*DelTaskResp, error)
		GetTaskById(ctx context.Context, in *GetTaskByIdReq, opts ...grpc.CallOption) (*GetTaskByIdResp, error)
		SearchTask(ctx context.Context, in *SearchTaskReq, opts ...grpc.CallOption) (*SearchTaskResp, error)
		// -----------------------taskFinish-----------------------
		AddTaskFinish(ctx context.Context, in *AddTaskFinishReq, opts ...grpc.CallOption) (*AddTaskFinishResp, error)
		UpdateTaskFinish(ctx context.Context, in *UpdateTaskFinishReq, opts ...grpc.CallOption) (*UpdateTaskFinishResp, error)
		DelTaskFinish(ctx context.Context, in *DelTaskFinishReq, opts ...grpc.CallOption) (*DelTaskFinishResp, error)
		GetTaskFinishById(ctx context.Context, in *GetTaskFinishByIdReq, opts ...grpc.CallOption) (*GetTaskFinishByIdResp, error)
		SearchTaskFinish(ctx context.Context, in *SearchTaskFinishReq, opts ...grpc.CallOption) (*SearchTaskFinishResp, error)
	}

	defaultSignin struct {
		cli zrpc.Client
	}
)

func NewSignin(cli zrpc.Client) Signin {
	return &defaultSignin{
		cli: cli,
	}
}

// -----------------------recode-----------------------
func (m *defaultSignin) AddRecode(ctx context.Context, in *AddRecodeReq, opts ...grpc.CallOption) (*AddRecodeResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.AddRecode(ctx, in, opts...)
}

func (m *defaultSignin) UpdateRecode(ctx context.Context, in *UpdateRecodeReq, opts ...grpc.CallOption) (*UpdateRecodeResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.UpdateRecode(ctx, in, opts...)
}

func (m *defaultSignin) DelRecode(ctx context.Context, in *DelRecodeReq, opts ...grpc.CallOption) (*DelRecodeResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.DelRecode(ctx, in, opts...)
}

func (m *defaultSignin) GetRecodeById(ctx context.Context, in *GetRecodeByIdReq, opts ...grpc.CallOption) (*GetRecodeByIdResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.GetRecodeById(ctx, in, opts...)
}

func (m *defaultSignin) SearchRecode(ctx context.Context, in *SearchRecodeReq, opts ...grpc.CallOption) (*SearchRecodeResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.SearchRecode(ctx, in, opts...)
}

// -----------------------task-----------------------
func (m *defaultSignin) AddTask(ctx context.Context, in *AddTaskReq, opts ...grpc.CallOption) (*AddTaskResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.AddTask(ctx, in, opts...)
}

func (m *defaultSignin) UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.UpdateTask(ctx, in, opts...)
}

func (m *defaultSignin) DelTask(ctx context.Context, in *DelTaskReq, opts ...grpc.CallOption) (*DelTaskResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.DelTask(ctx, in, opts...)
}

func (m *defaultSignin) GetTaskById(ctx context.Context, in *GetTaskByIdReq, opts ...grpc.CallOption) (*GetTaskByIdResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.GetTaskById(ctx, in, opts...)
}

func (m *defaultSignin) SearchTask(ctx context.Context, in *SearchTaskReq, opts ...grpc.CallOption) (*SearchTaskResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.SearchTask(ctx, in, opts...)
}

// -----------------------taskFinish-----------------------
func (m *defaultSignin) AddTaskFinish(ctx context.Context, in *AddTaskFinishReq, opts ...grpc.CallOption) (*AddTaskFinishResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.AddTaskFinish(ctx, in, opts...)
}

func (m *defaultSignin) UpdateTaskFinish(ctx context.Context, in *UpdateTaskFinishReq, opts ...grpc.CallOption) (*UpdateTaskFinishResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.UpdateTaskFinish(ctx, in, opts...)
}

func (m *defaultSignin) DelTaskFinish(ctx context.Context, in *DelTaskFinishReq, opts ...grpc.CallOption) (*DelTaskFinishResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.DelTaskFinish(ctx, in, opts...)
}

func (m *defaultSignin) GetTaskFinishById(ctx context.Context, in *GetTaskFinishByIdReq, opts ...grpc.CallOption) (*GetTaskFinishByIdResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.GetTaskFinishById(ctx, in, opts...)
}

func (m *defaultSignin) SearchTaskFinish(ctx context.Context, in *SearchTaskFinishReq, opts ...grpc.CallOption) (*SearchTaskFinishResp, error) {
	client := pb.NewSigninClient(m.cli.Conn())
	return client.SearchTaskFinish(ctx, in, opts...)
}
