global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'usercenter-api'
    static_configs:
      - targets: ['looklook:4008']
        labels:
          job: usercenter-api
          app: usercenter-api
          env: dev
  - job_name: 'usercenter-rpc'
    static_configs:
      - targets: ['looklook:4009']
        labels:
          job: usercenter-rpc
          app: usercenter-rpc
          env: dev
  - job_name: 'mqueue-job'
    static_configs:
      - targets: [ 'looklook:4010' ]
        labels:
          job: mqueue-job
          app: mqueue-job
          env: dev
  - job_name: 'mqueue-scheduler'
    static_configs:
      - targets: [ 'looklook:4011' ]
        labels:
          job: mqueue-scheduler
          app: mqueue-scheduler
          env: dev

  - job_name: 'reminder-api'
    static_configs:
      - targets: [ 'looklook:4012' ]
        labels:
          job: reminder-api
          app: reminder-api
          env: dev
  - job_name: 'reminder-rpc'
    static_configs:
      - targets: [ 'looklook:4013' ]
        labels:
          job: reminder-rpc
          app: reminder-rpc
          env: dev
  - job_name: 'recode-api'
    static_configs:
      - targets: [ 'looklook:4014' ]
        labels:
          job: recode-api
          app: recode-api
          env: dev
  - job_name: 'recode-rpc'
    static_configs:
      - targets: [ 'looklook:4015' ]
        labels:
          job: recode-rpc
          app: recode-rpc
          env: dev
  - job_name: 'upload-api'
    static_configs:
      - targets: [ 'looklook:4016' ]
        labels:
          job: upload-api
          app: upload-api
          env: dev
  - job_name: 'upload-rpc'
    static_configs:
      - targets: [ 'looklook:4017' ]
        labels:
          job: upload-rpc
          app: upload-rpc
          env: dev
  - job_name: 'signin-api'
    static_configs:
      - targets: [ 'looklook:4018' ]
        labels:
          job: signin-api
          app: signin-api
          env: dev
  - job_name: 'signin-rpc'
    static_configs:
      - targets: [ 'looklook:4019' ]
        labels:
          job: signin-rpc
          app: signin-rpc
          env: dev