// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"looklook/common/globalkey"
)

var (
	pointsRecodeFieldNames          = builder.RawFieldNames(&PointsRecode{})
	pointsRecodeRows                = strings.Join(pointsRecodeFieldNames, ",")
	pointsRecodeRowsExpectAutoSet   = strings.Join(stringx.Remove(pointsRecodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	pointsRecodeRowsWithPlaceHolder = strings.Join(stringx.Remove(pointsRecodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLooklookUsercenterPointsRecodeIdPrefix = "cache:looklookUsercenter:pointsRecode:id:"
)

type (
	pointsRecodeModel interface {
		Insert(ctx context.Context, data *PointsRecode) (sql.Result, error)
		TransInsert(ctx context.Context, session sqlx.Session, data *PointsRecode) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PointsRecode, error)
		Update(ctx context.Context, data *PointsRecode) error
		List(ctx context.Context, page, limit int64) ([]*PointsRecode, error)
		TransUpdate(ctx context.Context, session sqlx.Session, data *PointsRecode) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*PointsRecode, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*PointsRecode, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*PointsRecode, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*PointsRecode, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*PointsRecode, error)
		Delete(ctx context.Context, id int64) error
	}

	defaultPointsRecodeModel struct {
		sqlc.CachedConn
		table string
	}

	PointsRecode struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UserId     int64     `db:"user_id"`
		Points     int64     `db:"points"`  // 增减的积分数量
		Content    string    `db:"content"` // 原因备注
	}
)

func newPointsRecodeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPointsRecodeModel {
	return &defaultPointsRecodeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`points_recode`",
	}
}

func (m *defaultPointsRecodeModel) Delete(ctx context.Context, id int64) error {
	looklookUsercenterPointsRecodeIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterPointsRecodeIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, looklookUsercenterPointsRecodeIdKey)
	return err
}

func (m *defaultPointsRecodeModel) FindOne(ctx context.Context, id int64) (*PointsRecode, error) {
	looklookUsercenterPointsRecodeIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterPointsRecodeIdPrefix, id)
	var resp PointsRecode
	err := m.QueryRowCtx(ctx, &resp, looklookUsercenterPointsRecodeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pointsRecodeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPointsRecodeModel) Insert(ctx context.Context, data *PointsRecode) (sql.Result, error) {
	looklookUsercenterPointsRecodeIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterPointsRecodeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, pointsRecodeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Points, data.Content)
	}, looklookUsercenterPointsRecodeIdKey)
	return ret, err
}

func (m *defaultPointsRecodeModel) TransInsert(ctx context.Context, session sqlx.Session, data *PointsRecode) (sql.Result, error) {
	looklookUsercenterPointsRecodeIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterPointsRecodeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, pointsRecodeRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.UserId, data.Points, data.Content)
	}, looklookUsercenterPointsRecodeIdKey)
	return ret, err
}
func (m *defaultPointsRecodeModel) Update(ctx context.Context, data *PointsRecode) error {
	looklookUsercenterPointsRecodeIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterPointsRecodeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pointsRecodeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Points, data.Content, data.Id)
	}, looklookUsercenterPointsRecodeIdKey)
	return err
}

func (m *defaultPointsRecodeModel) TransUpdate(ctx context.Context, session sqlx.Session, data *PointsRecode) error {
	looklookUsercenterPointsRecodeIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterPointsRecodeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pointsRecodeRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.UserId, data.Points, data.Content, data.Id)
	}, looklookUsercenterPointsRecodeIdKey)
	return err
}

func (m *defaultPointsRecodeModel) List(ctx context.Context, page, limit int64) ([]*PointsRecode, error) {
	query := fmt.Sprintf("select %s from %s limit ?,?", pointsRecodeRows, m.table)
	var resp []*PointsRecode
	//err := m.conn.QueryRowsCtx(ctx, &resp, query, (page-1)*limit, limit)
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, (page-1)*limit, limit)
	return resp, err
}

func (m *defaultPointsRecodeModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultPointsRecodeModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultPointsRecodeModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultPointsRecodeModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*PointsRecode, error) {

	builder = builder.Columns(pointsRecodeRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PointsRecode
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPointsRecodeModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*PointsRecode, error) {

	builder = builder.Columns(pointsRecodeRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PointsRecode
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPointsRecodeModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*PointsRecode, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(pointsRecodeRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*PointsRecode
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultPointsRecodeModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*PointsRecode, error) {

	builder = builder.Columns(pointsRecodeRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PointsRecode
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPointsRecodeModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*PointsRecode, error) {

	builder = builder.Columns(pointsRecodeRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*PointsRecode
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPointsRecodeModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}

func (m *defaultPointsRecodeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLooklookUsercenterPointsRecodeIdPrefix, primary)
}

func (m *defaultPointsRecodeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pointsRecodeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPointsRecodeModel) tableName() string {
	return m.table
}
