/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LotteryTabbar: typeof import('./src/components/lotteryTabbar.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutAnimate: typeof import('@nutui/nutui-taro')['Animate']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutAvatarGroup: typeof import('@nutui/nutui-taro')['AvatarGroup']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCard: typeof import('@nutui/nutui-taro')['Card']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCollapse: typeof import('@nutui/nutui-taro')['Collapse']
    NutCollapseItem: typeof import('@nutui/nutui-taro')['CollapseItem']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutNotify: typeof import('@nutui/nutui-taro')['Notify']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSpace: typeof import('@nutui/nutui-taro')['Space']
    NutSwipe: typeof import('@nutui/nutui-taro')['Swipe']
    NutSwipeGroup: typeof import('@nutui/nutui-taro')['SwipeGroup']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
  }
}
