// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: lottery.proto

package lottery

import (
	"context"

	"looklook/app/lottery/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddLotteryParticipationReq         = pb.AddLotteryParticipationReq
	AddLotteryParticipationResp        = pb.AddLotteryParticipationResp
	AddLotteryReq                      = pb.AddLotteryReq
	AddLotteryResp                     = pb.AddLotteryResp
	AddPrizeReq                        = pb.AddPrizeReq
	AddPrizeResp                       = pb.AddPrizeResp
	DelLotteryParticipationReq         = pb.DelLotteryParticipationReq
	DelLotteryParticipationResp        = pb.DelLotteryParticipationResp
	DelLotteryReq                      = pb.DelLotteryReq
	DelLotteryResp                     = pb.DelLotteryResp
	DelPrizeReq                        = pb.DelPrizeReq
	DelPrizeResp                       = pb.DelPrizeResp
	GetLotteryByIdReq                  = pb.GetLotteryByIdReq
	GetLotteryByIdResp                 = pb.GetLotteryByIdResp
	GetLotteryParticipationByIdReq     = pb.GetLotteryParticipationByIdReq
	GetLotteryParticipationByIdResp    = pb.GetLotteryParticipationByIdResp
	GetPrizeByIdReq                    = pb.GetPrizeByIdReq
	GetPrizeByIdResp                   = pb.GetPrizeByIdResp
	Lottery                            = pb.Lottery
	LotteryParticipation               = pb.LotteryParticipation
	Prize                              = pb.Prize
	SearchLotteryParticipationReq      = pb.SearchLotteryParticipationReq
	SearchLotteryParticipationResp     = pb.SearchLotteryParticipationResp
	SearchLotteryParticipationWinReq   = pb.SearchLotteryParticipationWinReq
	SearchLotteryParticipationWinResp  = pb.SearchLotteryParticipationWinResp
	SearchLotteryReq                   = pb.SearchLotteryReq
	SearchLotteryResp                  = pb.SearchLotteryResp
	SearchPrizeReq                     = pb.SearchPrizeReq
	SearchPrizeResp                    = pb.SearchPrizeResp
	SearchUserLotteryParticipationReq  = pb.SearchUserLotteryParticipationReq
	SearchUserLotteryParticipationResp = pb.SearchUserLotteryParticipationResp
	UpdateLotteryParticipationReq      = pb.UpdateLotteryParticipationReq
	UpdateLotteryParticipationResp     = pb.UpdateLotteryParticipationResp
	UpdateLotteryReq                   = pb.UpdateLotteryReq
	UpdateLotteryResp                  = pb.UpdateLotteryResp
	UpdatePrizeReq                     = pb.UpdatePrizeReq
	UpdatePrizeResp                    = pb.UpdatePrizeResp
	UserLottery                        = pb.UserLottery

	LotteryZrpcClient interface {
		// -----------------------鎶藉琛?----------------------
		AddLottery(ctx context.Context, in *AddLotteryReq, opts ...grpc.CallOption) (*AddLotteryResp, error)
		UpdateLottery(ctx context.Context, in *UpdateLotteryReq, opts ...grpc.CallOption) (*UpdateLotteryResp, error)
		DelLottery(ctx context.Context, in *DelLotteryReq, opts ...grpc.CallOption) (*DelLotteryResp, error)
		GetLotteryById(ctx context.Context, in *GetLotteryByIdReq, opts ...grpc.CallOption) (*GetLotteryByIdResp, error)
		SearchLottery(ctx context.Context, in *SearchLotteryReq, opts ...grpc.CallOption) (*SearchLotteryResp, error)
		// -----------------------鍙備笌鎶藉-----------------------
		AddLotteryParticipation(ctx context.Context, in *AddLotteryParticipationReq, opts ...grpc.CallOption) (*AddLotteryParticipationResp, error)
		UpdateLotteryParticipation(ctx context.Context, in *UpdateLotteryParticipationReq, opts ...grpc.CallOption) (*UpdateLotteryParticipationResp, error)
		DelLotteryParticipation(ctx context.Context, in *DelLotteryParticipationReq, opts ...grpc.CallOption) (*DelLotteryParticipationResp, error)
		GetLotteryParticipationById(ctx context.Context, in *GetLotteryParticipationByIdReq, opts ...grpc.CallOption) (*GetLotteryParticipationByIdResp, error)
		SearchLotteryParticipation(ctx context.Context, in *SearchLotteryParticipationReq, opts ...grpc.CallOption) (*SearchLotteryParticipationResp, error)
		SearchUserLotteryParticipation(ctx context.Context, in *SearchUserLotteryParticipationReq, opts ...grpc.CallOption) (*SearchUserLotteryParticipationResp, error)
		SearchLotteryParticipationWin(ctx context.Context, in *SearchLotteryParticipationWinReq, opts ...grpc.CallOption) (*SearchLotteryParticipationWinResp, error)
		// -----------------------濂栧搧琛?----------------------
		AddPrize(ctx context.Context, in *AddPrizeReq, opts ...grpc.CallOption) (*AddPrizeResp, error)
		UpdatePrize(ctx context.Context, in *UpdatePrizeReq, opts ...grpc.CallOption) (*UpdatePrizeResp, error)
		DelPrize(ctx context.Context, in *DelPrizeReq, opts ...grpc.CallOption) (*DelPrizeResp, error)
		GetPrizeById(ctx context.Context, in *GetPrizeByIdReq, opts ...grpc.CallOption) (*GetPrizeByIdResp, error)
		SearchPrize(ctx context.Context, in *SearchPrizeReq, opts ...grpc.CallOption) (*SearchPrizeResp, error)
	}

	defaultLotteryZrpcClient struct {
		cli zrpc.Client
	}
)

func NewLotteryZrpcClient(cli zrpc.Client) LotteryZrpcClient {
	return &defaultLotteryZrpcClient{
		cli: cli,
	}
}

// -----------------------鎶藉琛?----------------------
func (m *defaultLotteryZrpcClient) AddLottery(ctx context.Context, in *AddLotteryReq, opts ...grpc.CallOption) (*AddLotteryResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.AddLottery(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) UpdateLottery(ctx context.Context, in *UpdateLotteryReq, opts ...grpc.CallOption) (*UpdateLotteryResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.UpdateLottery(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) DelLottery(ctx context.Context, in *DelLotteryReq, opts ...grpc.CallOption) (*DelLotteryResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.DelLottery(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) GetLotteryById(ctx context.Context, in *GetLotteryByIdReq, opts ...grpc.CallOption) (*GetLotteryByIdResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.GetLotteryById(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) SearchLottery(ctx context.Context, in *SearchLotteryReq, opts ...grpc.CallOption) (*SearchLotteryResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.SearchLottery(ctx, in, opts...)
}

// -----------------------鍙備笌鎶藉-----------------------
func (m *defaultLotteryZrpcClient) AddLotteryParticipation(ctx context.Context, in *AddLotteryParticipationReq, opts ...grpc.CallOption) (*AddLotteryParticipationResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.AddLotteryParticipation(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) UpdateLotteryParticipation(ctx context.Context, in *UpdateLotteryParticipationReq, opts ...grpc.CallOption) (*UpdateLotteryParticipationResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.UpdateLotteryParticipation(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) DelLotteryParticipation(ctx context.Context, in *DelLotteryParticipationReq, opts ...grpc.CallOption) (*DelLotteryParticipationResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.DelLotteryParticipation(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) GetLotteryParticipationById(ctx context.Context, in *GetLotteryParticipationByIdReq, opts ...grpc.CallOption) (*GetLotteryParticipationByIdResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.GetLotteryParticipationById(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) SearchLotteryParticipation(ctx context.Context, in *SearchLotteryParticipationReq, opts ...grpc.CallOption) (*SearchLotteryParticipationResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.SearchLotteryParticipation(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) SearchUserLotteryParticipation(ctx context.Context, in *SearchUserLotteryParticipationReq, opts ...grpc.CallOption) (*SearchUserLotteryParticipationResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.SearchUserLotteryParticipation(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) SearchLotteryParticipationWin(ctx context.Context, in *SearchLotteryParticipationWinReq, opts ...grpc.CallOption) (*SearchLotteryParticipationWinResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.SearchLotteryParticipationWin(ctx, in, opts...)
}

// -----------------------濂栧搧琛?----------------------
func (m *defaultLotteryZrpcClient) AddPrize(ctx context.Context, in *AddPrizeReq, opts ...grpc.CallOption) (*AddPrizeResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.AddPrize(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) UpdatePrize(ctx context.Context, in *UpdatePrizeReq, opts ...grpc.CallOption) (*UpdatePrizeResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.UpdatePrize(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) DelPrize(ctx context.Context, in *DelPrizeReq, opts ...grpc.CallOption) (*DelPrizeResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.DelPrize(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) GetPrizeById(ctx context.Context, in *GetPrizeByIdReq, opts ...grpc.CallOption) (*GetPrizeByIdResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.GetPrizeById(ctx, in, opts...)
}

func (m *defaultLotteryZrpcClient) SearchPrize(ctx context.Context, in *SearchPrizeReq, opts ...grpc.CallOption) (*SearchPrizeResp, error) {
	client := pb.NewLotteryClient(m.cli.Conn())
	return client.SearchPrize(ctx, in, opts...)
}
