// Code generated by goctl. DO NOT EDIT.
package types

type AddRecodeTodayReq struct {
}

type AddRecodeTodayResp struct {
	Id int64 `json:"id"`
}

type ChangeSignRemindReq struct {
	Status int64 `json:"status"`
}

type ChangeSignRemindResp struct {
	Id     int64 `json:"id"`
	Status int64 `json:"status"`
}

type GetRemindStatusReq struct {
}

type GetRemindStatusResp struct {
	Status int64 `json:"status"`
}

type ListRecodeReq struct {
	LastId   int64 `form:"lastId"`
	Page     int64 `form:"page"`
	PageSize int64 `form:"pageSize"`
}

type ListRecodeResp struct {
	List    []Recode `json:"list"`
	Days    int64    `json:"days"`
	IsToday int64    `json:"isToday"`
}

type ListTaskReq struct {
	LastId   int64 `form:"lastId"`
	Page     int64 `form:"page"`
	PageSize int64 `form:"pageSize"`
}

type ListTaskResp struct {
	List []Task `json:"list"`
}

type Recode struct {
	Id       int64 `json:"id"`
	UserId   int64 `json:"userId"`
	SignDate int64 `json:"signDate"`
}

type Remind struct {
	Id     int64 `json:"id"`
	UserId int64 `json:"userId"`
	Status int64 `json:"status"`
}

type Task struct {
	Id         int64  `json:"id"`
	Title      string `json:"title"`      // 任务标题
	Type       int64  `json:"type"`       // 任务类型：1连续签到
	Value      int64  `json:"value"`      // 任务值，依据type来确定：为1时是连续天数
	Content    string `json:"content"`    // 备注
	Points     int64  `json:"points"`     // 获得的积分值
	IsFinished int64  `json:"isFinished"` // 1为完成
}

type TestReq struct {
	Age        int64  `json:"age" validate:"gte=1,lte=130"`
	Name       string `json:"name" validate:"required"`
	Email      string `json:"email" validate:"required,email"`
	Password   string `json:"password" validate:"required"`
	RePassword string `json:"re_password" validate:"required"`
	Date       string `json:"date" validate:"required,datetime=2006-01-02,checkDate"`
}

type TestResp struct {
}
