// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: usercenter.proto

package server

import (
	"context"

	"looklook/app/usercenter/cmd/rpc/internal/logic"
	"looklook/app/usercenter/cmd/rpc/internal/svc"
	"looklook/app/usercenter/cmd/rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UsercenterServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UsercenterServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UsercenterServer) GetUserAuthByAuthKey(ctx context.Context, in *pb.GetUserAuthByAuthKeyReq) (*pb.GetUserAuthByAuthKeyResp, error) {
	l := logic.NewGetUserAuthByAuthKeyLogic(ctx, s.svcCtx)
	return l.GetUserAuthByAuthKey(in)
}

func (s *UsercenterServer) GetUserAuthByUserId(ctx context.Context, in *pb.GetUserAuthByUserIdReq) (*pb.GetUserAuthyUserIdResp, error) {
	l := logic.NewGetUserAuthByUserIdLogic(ctx, s.svcCtx)
	return l.GetUserAuthByUserId(in)
}

func (s *UsercenterServer) GenerateToken(ctx context.Context, in *pb.GenerateTokenReq) (*pb.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

func (s *UsercenterServer) BindIntimate(ctx context.Context, in *pb.BindIntimateReq) (*pb.BindIntimateResp, error) {
	l := logic.NewBindIntimateLogic(ctx, s.svcCtx)
	return l.BindIntimate(in)
}

func (s *UsercenterServer) CancelBindIntimate(ctx context.Context, in *pb.CancelBindIntimateReq) (*pb.CancelBindIntimateResp, error) {
	l := logic.NewCancelBindIntimateLogic(ctx, s.svcCtx)
	return l.CancelBindIntimate(in)
}

func (s *UsercenterServer) ModifyUserInfo(ctx context.Context, in *pb.ModifyUserInfoReq) (*pb.ModifyUserInfoResp, error) {
	l := logic.NewModifyUserInfoLogic(ctx, s.svcCtx)
	return l.ModifyUserInfo(in)
}

func (s *UsercenterServer) AddPointsRecode(ctx context.Context, in *pb.AddPointsRecodeReq) (*pb.AddPointsRecodeResp, error) {
	l := logic.NewAddPointsRecodeLogic(ctx, s.svcCtx)
	return l.AddPointsRecode(in)
}

func (s *UsercenterServer) AddPointsRecodeRollback(ctx context.Context, in *pb.AddPointsRecodeReq) (*pb.AddPointsRecodeResp, error) {
	l := logic.NewAddPointsRecodeRollbackLogic(ctx, s.svcCtx)
	return l.AddPointsRecodeRollback(in)
}

func (s *UsercenterServer) PointsRecodeList(ctx context.Context, in *pb.PointsRecodeListReq) (*pb.PointRecodeListResp, error) {
	l := logic.NewPointsRecodeListLogic(ctx, s.svcCtx)
	return l.PointsRecodeList(in)
}
