// Code generated by goctl. DO NOT EDIT.
package types

type CreateItemsReq struct {
	Content string `json:"content"` //事项名
	Member  int64  `json:"member"`  //0自己，1贡献
}

type CreateItemsResp struct {
	Id int `json:"id"`
}

type CreateRecodeReq struct {
	ItemsId    int64  `json:"itemsId"`
	Content    string `json:"content"`
	RecodeTime int64  `json:"recodeTime"`
}

type CreateRecodeResp struct {
	Id int `json:"id"`
}

type DeleteItemsReq struct {
	Id int `json:"id"`
}

type DeleteItemsResp struct {
	Id int `json:"id"`
}

type DeleteRecodeReq struct {
	Id int `json:"id"`
}

type DeleteRecodeResp struct {
	Id int `json:"id"`
}

type Items struct {
	Id      int64  `json:"id"`
	UserId  int64  `json:"userId"`  //发起事项用户ID
	Content string `json:"content"` //事项名
	Member  int64  `json:"member"`  //0自己，1贡献
}

type ItemsByIdReq struct {
	Id int `form:"id"`
}

type ItemsByIdResp struct {
	Recode Items `json:"items"`
}

type ItemsListReq struct {
	LastId   int64 `form:"lastId"`
	Page     int64 `form:"page"`
	PageSize int64 `form:"pageSize"`
}

type ItemsListResp struct {
	List []Items `json:"list"`
}

type ModifyItemsReq struct {
	Id      int64  `json:"id"`
	Content string `json:"content"` //事项名
	Member  int64  `json:"member"`  //0自己，1贡献
}

type ModifyItemsResp struct {
	Id int `json:"id"`
}

type ModifyRecodeReq struct {
	Id      int64  `json:"id"`
	Content string `json:"content"` //事项名
}

type ModifyRecodeResp struct {
	Id int `json:"id"`
}

type Recode struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId"` //发起事项用户ID
	ItemsId    int64  `json:"itemsId"`
	Content    string `json:"content"` //事项名
	RecodeTime int64  `json:"recodeTime"`
}

type RecodeByIdReq struct {
	Id int `form:"id"`
}

type RecodeByIdResp struct {
	Recode Recode `json:"recode"`
}

type RecodeListReq struct {
	LastId   int64 `form:"lastId"`
	Page     int64 `form:"page"`
	PageSize int64 `form:"pageSize"`
	ItemsId  int64 `form:"itemsId"`
}

type RecodeListResp struct {
	List            []Recode `json:"list"`
	RecodeDayCount  int64    `json:"recodeDayCount"`
	RecodeDaySpaced float32  `json:"recodeDaySpaced"`
}
