// Code generated by goctl. DO NOT EDIT.
package types

type UserUploadReq struct {
	FileName string `json:"file_name,optional"`
	Ext      string `json:"ext,optional"`
	Size     int64  `json:"size,optional"`
	FileData []byte `json:"file_data,optional"`
}

type UserUploadRes struct {
	Url string `json:"url"`
}
