// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: lottery.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lottery_AddLottery_FullMethodName                  = "/pb.lottery/AddLottery"
	Lottery_UpdateLottery_FullMethodName               = "/pb.lottery/UpdateLottery"
	Lottery_DelLottery_FullMethodName                  = "/pb.lottery/DelLottery"
	Lottery_GetLotteryById_FullMethodName              = "/pb.lottery/GetLotteryById"
	Lottery_SearchLottery_FullMethodName               = "/pb.lottery/SearchLottery"
	Lottery_AddLotteryParticipation_FullMethodName     = "/pb.lottery/AddLotteryParticipation"
	Lottery_UpdateLotteryParticipation_FullMethodName  = "/pb.lottery/UpdateLotteryParticipation"
	Lottery_DelLotteryParticipation_FullMethodName     = "/pb.lottery/DelLotteryParticipation"
	Lottery_GetLotteryParticipationById_FullMethodName = "/pb.lottery/GetLotteryParticipationById"
	Lottery_SearchLotteryParticipation_FullMethodName  = "/pb.lottery/SearchLotteryParticipation"
	Lottery_AddPrize_FullMethodName                    = "/pb.lottery/AddPrize"
	Lottery_UpdatePrize_FullMethodName                 = "/pb.lottery/UpdatePrize"
	Lottery_DelPrize_FullMethodName                    = "/pb.lottery/DelPrize"
	Lottery_GetPrizeById_FullMethodName                = "/pb.lottery/GetPrizeById"
	Lottery_SearchPrize_FullMethodName                 = "/pb.lottery/SearchPrize"
)

// LotteryClient is the client API for Lottery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotteryClient interface {
	// -----------------------鎶藉琛?----------------------
	AddLottery(ctx context.Context, in *AddLotteryReq, opts ...grpc.CallOption) (*AddLotteryResp, error)
	UpdateLottery(ctx context.Context, in *UpdateLotteryReq, opts ...grpc.CallOption) (*UpdateLotteryResp, error)
	DelLottery(ctx context.Context, in *DelLotteryReq, opts ...grpc.CallOption) (*DelLotteryResp, error)
	GetLotteryById(ctx context.Context, in *GetLotteryByIdReq, opts ...grpc.CallOption) (*GetLotteryByIdResp, error)
	SearchLottery(ctx context.Context, in *SearchLotteryReq, opts ...grpc.CallOption) (*SearchLotteryResp, error)
	// -----------------------鍙備笌鎶藉-----------------------
	AddLotteryParticipation(ctx context.Context, in *AddLotteryParticipationReq, opts ...grpc.CallOption) (*AddLotteryParticipationResp, error)
	UpdateLotteryParticipation(ctx context.Context, in *UpdateLotteryParticipationReq, opts ...grpc.CallOption) (*UpdateLotteryParticipationResp, error)
	DelLotteryParticipation(ctx context.Context, in *DelLotteryParticipationReq, opts ...grpc.CallOption) (*DelLotteryParticipationResp, error)
	GetLotteryParticipationById(ctx context.Context, in *GetLotteryParticipationByIdReq, opts ...grpc.CallOption) (*GetLotteryParticipationByIdResp, error)
	SearchLotteryParticipation(ctx context.Context, in *SearchLotteryParticipationReq, opts ...grpc.CallOption) (*SearchLotteryParticipationResp, error)
	// -----------------------濂栧搧琛?----------------------
	AddPrize(ctx context.Context, in *AddPrizeReq, opts ...grpc.CallOption) (*AddPrizeResp, error)
	UpdatePrize(ctx context.Context, in *UpdatePrizeReq, opts ...grpc.CallOption) (*UpdatePrizeResp, error)
	DelPrize(ctx context.Context, in *DelPrizeReq, opts ...grpc.CallOption) (*DelPrizeResp, error)
	GetPrizeById(ctx context.Context, in *GetPrizeByIdReq, opts ...grpc.CallOption) (*GetPrizeByIdResp, error)
	SearchPrize(ctx context.Context, in *SearchPrizeReq, opts ...grpc.CallOption) (*SearchPrizeResp, error)
}

type lotteryClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryClient(cc grpc.ClientConnInterface) LotteryClient {
	return &lotteryClient{cc}
}

func (c *lotteryClient) AddLottery(ctx context.Context, in *AddLotteryReq, opts ...grpc.CallOption) (*AddLotteryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLotteryResp)
	err := c.cc.Invoke(ctx, Lottery_AddLottery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) UpdateLottery(ctx context.Context, in *UpdateLotteryReq, opts ...grpc.CallOption) (*UpdateLotteryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLotteryResp)
	err := c.cc.Invoke(ctx, Lottery_UpdateLottery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) DelLottery(ctx context.Context, in *DelLotteryReq, opts ...grpc.CallOption) (*DelLotteryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelLotteryResp)
	err := c.cc.Invoke(ctx, Lottery_DelLottery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) GetLotteryById(ctx context.Context, in *GetLotteryByIdReq, opts ...grpc.CallOption) (*GetLotteryByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLotteryByIdResp)
	err := c.cc.Invoke(ctx, Lottery_GetLotteryById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) SearchLottery(ctx context.Context, in *SearchLotteryReq, opts ...grpc.CallOption) (*SearchLotteryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchLotteryResp)
	err := c.cc.Invoke(ctx, Lottery_SearchLottery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) AddLotteryParticipation(ctx context.Context, in *AddLotteryParticipationReq, opts ...grpc.CallOption) (*AddLotteryParticipationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLotteryParticipationResp)
	err := c.cc.Invoke(ctx, Lottery_AddLotteryParticipation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) UpdateLotteryParticipation(ctx context.Context, in *UpdateLotteryParticipationReq, opts ...grpc.CallOption) (*UpdateLotteryParticipationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLotteryParticipationResp)
	err := c.cc.Invoke(ctx, Lottery_UpdateLotteryParticipation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) DelLotteryParticipation(ctx context.Context, in *DelLotteryParticipationReq, opts ...grpc.CallOption) (*DelLotteryParticipationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelLotteryParticipationResp)
	err := c.cc.Invoke(ctx, Lottery_DelLotteryParticipation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) GetLotteryParticipationById(ctx context.Context, in *GetLotteryParticipationByIdReq, opts ...grpc.CallOption) (*GetLotteryParticipationByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLotteryParticipationByIdResp)
	err := c.cc.Invoke(ctx, Lottery_GetLotteryParticipationById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) SearchLotteryParticipation(ctx context.Context, in *SearchLotteryParticipationReq, opts ...grpc.CallOption) (*SearchLotteryParticipationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchLotteryParticipationResp)
	err := c.cc.Invoke(ctx, Lottery_SearchLotteryParticipation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) AddPrize(ctx context.Context, in *AddPrizeReq, opts ...grpc.CallOption) (*AddPrizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPrizeResp)
	err := c.cc.Invoke(ctx, Lottery_AddPrize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) UpdatePrize(ctx context.Context, in *UpdatePrizeReq, opts ...grpc.CallOption) (*UpdatePrizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePrizeResp)
	err := c.cc.Invoke(ctx, Lottery_UpdatePrize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) DelPrize(ctx context.Context, in *DelPrizeReq, opts ...grpc.CallOption) (*DelPrizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelPrizeResp)
	err := c.cc.Invoke(ctx, Lottery_DelPrize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) GetPrizeById(ctx context.Context, in *GetPrizeByIdReq, opts ...grpc.CallOption) (*GetPrizeByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrizeByIdResp)
	err := c.cc.Invoke(ctx, Lottery_GetPrizeById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) SearchPrize(ctx context.Context, in *SearchPrizeReq, opts ...grpc.CallOption) (*SearchPrizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPrizeResp)
	err := c.cc.Invoke(ctx, Lottery_SearchPrize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotteryServer is the server API for Lottery service.
// All implementations must embed UnimplementedLotteryServer
// for forward compatibility.
type LotteryServer interface {
	// -----------------------鎶藉琛?----------------------
	AddLottery(context.Context, *AddLotteryReq) (*AddLotteryResp, error)
	UpdateLottery(context.Context, *UpdateLotteryReq) (*UpdateLotteryResp, error)
	DelLottery(context.Context, *DelLotteryReq) (*DelLotteryResp, error)
	GetLotteryById(context.Context, *GetLotteryByIdReq) (*GetLotteryByIdResp, error)
	SearchLottery(context.Context, *SearchLotteryReq) (*SearchLotteryResp, error)
	// -----------------------鍙備笌鎶藉-----------------------
	AddLotteryParticipation(context.Context, *AddLotteryParticipationReq) (*AddLotteryParticipationResp, error)
	UpdateLotteryParticipation(context.Context, *UpdateLotteryParticipationReq) (*UpdateLotteryParticipationResp, error)
	DelLotteryParticipation(context.Context, *DelLotteryParticipationReq) (*DelLotteryParticipationResp, error)
	GetLotteryParticipationById(context.Context, *GetLotteryParticipationByIdReq) (*GetLotteryParticipationByIdResp, error)
	SearchLotteryParticipation(context.Context, *SearchLotteryParticipationReq) (*SearchLotteryParticipationResp, error)
	// -----------------------濂栧搧琛?----------------------
	AddPrize(context.Context, *AddPrizeReq) (*AddPrizeResp, error)
	UpdatePrize(context.Context, *UpdatePrizeReq) (*UpdatePrizeResp, error)
	DelPrize(context.Context, *DelPrizeReq) (*DelPrizeResp, error)
	GetPrizeById(context.Context, *GetPrizeByIdReq) (*GetPrizeByIdResp, error)
	SearchPrize(context.Context, *SearchPrizeReq) (*SearchPrizeResp, error)
	mustEmbedUnimplementedLotteryServer()
}

// UnimplementedLotteryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotteryServer struct{}

func (UnimplementedLotteryServer) AddLottery(context.Context, *AddLotteryReq) (*AddLotteryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLottery not implemented")
}
func (UnimplementedLotteryServer) UpdateLottery(context.Context, *UpdateLotteryReq) (*UpdateLotteryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLottery not implemented")
}
func (UnimplementedLotteryServer) DelLottery(context.Context, *DelLotteryReq) (*DelLotteryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelLottery not implemented")
}
func (UnimplementedLotteryServer) GetLotteryById(context.Context, *GetLotteryByIdReq) (*GetLotteryByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLotteryById not implemented")
}
func (UnimplementedLotteryServer) SearchLottery(context.Context, *SearchLotteryReq) (*SearchLotteryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchLottery not implemented")
}
func (UnimplementedLotteryServer) AddLotteryParticipation(context.Context, *AddLotteryParticipationReq) (*AddLotteryParticipationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLotteryParticipation not implemented")
}
func (UnimplementedLotteryServer) UpdateLotteryParticipation(context.Context, *UpdateLotteryParticipationReq) (*UpdateLotteryParticipationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLotteryParticipation not implemented")
}
func (UnimplementedLotteryServer) DelLotteryParticipation(context.Context, *DelLotteryParticipationReq) (*DelLotteryParticipationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelLotteryParticipation not implemented")
}
func (UnimplementedLotteryServer) GetLotteryParticipationById(context.Context, *GetLotteryParticipationByIdReq) (*GetLotteryParticipationByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLotteryParticipationById not implemented")
}
func (UnimplementedLotteryServer) SearchLotteryParticipation(context.Context, *SearchLotteryParticipationReq) (*SearchLotteryParticipationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchLotteryParticipation not implemented")
}
func (UnimplementedLotteryServer) AddPrize(context.Context, *AddPrizeReq) (*AddPrizeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPrize not implemented")
}
func (UnimplementedLotteryServer) UpdatePrize(context.Context, *UpdatePrizeReq) (*UpdatePrizeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePrize not implemented")
}
func (UnimplementedLotteryServer) DelPrize(context.Context, *DelPrizeReq) (*DelPrizeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelPrize not implemented")
}
func (UnimplementedLotteryServer) GetPrizeById(context.Context, *GetPrizeByIdReq) (*GetPrizeByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrizeById not implemented")
}
func (UnimplementedLotteryServer) SearchPrize(context.Context, *SearchPrizeReq) (*SearchPrizeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPrize not implemented")
}
func (UnimplementedLotteryServer) mustEmbedUnimplementedLotteryServer() {}
func (UnimplementedLotteryServer) testEmbeddedByValue()                 {}

// UnsafeLotteryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotteryServer will
// result in compilation errors.
type UnsafeLotteryServer interface {
	mustEmbedUnimplementedLotteryServer()
}

func RegisterLotteryServer(s grpc.ServiceRegistrar, srv LotteryServer) {
	// If the following call pancis, it indicates UnimplementedLotteryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lottery_ServiceDesc, srv)
}

func _Lottery_AddLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLotteryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).AddLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_AddLottery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).AddLottery(ctx, req.(*AddLotteryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_UpdateLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLotteryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).UpdateLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_UpdateLottery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).UpdateLottery(ctx, req.(*UpdateLotteryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_DelLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelLotteryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).DelLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_DelLottery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).DelLottery(ctx, req.(*DelLotteryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_GetLotteryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLotteryByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).GetLotteryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_GetLotteryById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).GetLotteryById(ctx, req.(*GetLotteryByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_SearchLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLotteryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).SearchLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_SearchLottery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).SearchLottery(ctx, req.(*SearchLotteryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_AddLotteryParticipation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLotteryParticipationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).AddLotteryParticipation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_AddLotteryParticipation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).AddLotteryParticipation(ctx, req.(*AddLotteryParticipationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_UpdateLotteryParticipation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLotteryParticipationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).UpdateLotteryParticipation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_UpdateLotteryParticipation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).UpdateLotteryParticipation(ctx, req.(*UpdateLotteryParticipationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_DelLotteryParticipation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelLotteryParticipationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).DelLotteryParticipation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_DelLotteryParticipation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).DelLotteryParticipation(ctx, req.(*DelLotteryParticipationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_GetLotteryParticipationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLotteryParticipationByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).GetLotteryParticipationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_GetLotteryParticipationById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).GetLotteryParticipationById(ctx, req.(*GetLotteryParticipationByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_SearchLotteryParticipation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLotteryParticipationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).SearchLotteryParticipation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_SearchLotteryParticipation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).SearchLotteryParticipation(ctx, req.(*SearchLotteryParticipationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_AddPrize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPrizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).AddPrize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_AddPrize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).AddPrize(ctx, req.(*AddPrizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_UpdatePrize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePrizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).UpdatePrize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_UpdatePrize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).UpdatePrize(ctx, req.(*UpdatePrizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_DelPrize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPrizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).DelPrize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_DelPrize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).DelPrize(ctx, req.(*DelPrizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_GetPrizeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrizeByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).GetPrizeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_GetPrizeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).GetPrizeById(ctx, req.(*GetPrizeByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_SearchPrize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPrizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).SearchPrize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lottery_SearchPrize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).SearchPrize(ctx, req.(*SearchPrizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Lottery_ServiceDesc is the grpc.ServiceDesc for Lottery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lottery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.lottery",
	HandlerType: (*LotteryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLottery",
			Handler:    _Lottery_AddLottery_Handler,
		},
		{
			MethodName: "UpdateLottery",
			Handler:    _Lottery_UpdateLottery_Handler,
		},
		{
			MethodName: "DelLottery",
			Handler:    _Lottery_DelLottery_Handler,
		},
		{
			MethodName: "GetLotteryById",
			Handler:    _Lottery_GetLotteryById_Handler,
		},
		{
			MethodName: "SearchLottery",
			Handler:    _Lottery_SearchLottery_Handler,
		},
		{
			MethodName: "AddLotteryParticipation",
			Handler:    _Lottery_AddLotteryParticipation_Handler,
		},
		{
			MethodName: "UpdateLotteryParticipation",
			Handler:    _Lottery_UpdateLotteryParticipation_Handler,
		},
		{
			MethodName: "DelLotteryParticipation",
			Handler:    _Lottery_DelLotteryParticipation_Handler,
		},
		{
			MethodName: "GetLotteryParticipationById",
			Handler:    _Lottery_GetLotteryParticipationById_Handler,
		},
		{
			MethodName: "SearchLotteryParticipation",
			Handler:    _Lottery_SearchLotteryParticipation_Handler,
		},
		{
			MethodName: "AddPrize",
			Handler:    _Lottery_AddPrize_Handler,
		},
		{
			MethodName: "UpdatePrize",
			Handler:    _Lottery_UpdatePrize_Handler,
		},
		{
			MethodName: "DelPrize",
			Handler:    _Lottery_DelPrize_Handler,
		},
		{
			MethodName: "GetPrizeById",
			Handler:    _Lottery_GetPrizeById_Handler,
		},
		{
			MethodName: "SearchPrize",
			Handler:    _Lottery_SearchPrize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery.proto",
}
