// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	lottery "looklook/app/lottery/cmd/api/internal/handler/lottery"
	"looklook/app/lottery/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 发起抽奖
				Method:  http.MethodPost,
				Path:    "/lottery/createLottery",
				Handler: lottery.CreateLotteryHandler(serverCtx),
			},
			{
				// lottery detail
				Method:  http.MethodGet,
				Path:    "/lottery/lotteryDetail",
				Handler: lottery.LotteryDetailHandler(serverCtx),
			},
			{
				// lottery list
				Method:  http.MethodGet,
				Path:    "/lottery/lotteryList",
				Handler: lottery.LotteryListHandler(serverCtx),
			},
			{
				// 发布抽奖
				Method:  http.MethodPost,
				Path:    "/lottery/updateLottery",
				Handler: lottery.UpdateLotteryHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/lottery/v1"),
	)
}
